blueprint:
  name: Motion-activated Light with Adjustable Brightness and Transition
  description: >-
    Turn on a light with specified brightness and transition times when motion
    is detected. Brightness changes based on time of day.
  domain: automation
  source_url: https://github.com/orHayoun/ha/blob/main/motion_light_v2.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait Time
      description: Time to leave the light on after the last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: "seconds"
    transition_time:
      name: Transition Time
      description: Time it takes for the light to turn on or off.
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: "seconds"
    day_brightness:
      name: Day Brightness
      default: 100
      selector:
        number:
          min: 0
          max: 255
    evening_brightness:
      name: Evening Brightness
      default: 70
      selector:
        number:
          min: 0
          max: 255
    night_brightness:
      name: Night Brightness
      default: 30
      selector:
        number:
          min: 0
          max: 255

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input "motion_entity"
  from: "off"
  to: "on"

action:
  - variables:
      current_hour: "{{ now().hour }}"
  - choose:
      - conditions: "{{ 6 <= current_hour < 18 }}"
        sequence:
          - service: light.turn_on
            target: !input "light_target"
            data:
              brightness: !input "day_brightness"
              transition: !input "transition_time
      - conditions: "{{ 18 <= current_hour < 22 }}"
        sequence:
          - service: light.turn_on
            target: !input "light_target"
            data:
              brightness: !input "evening_brightness"
              transition: !input "transition_time"
      - conditions: "{{ current_hour >= 22 or current_hour < 6 }}"
        sequence:
          - service: light.turn_on
            target: !input "light_target"
            data:
              brightness: !input "night_brightness"
              transition: !input "transition_time"
  - wait_for_trigger:
      platform: state
      entity_id: !input "motion_entity"
      from: "on"
      to: "off"
  - delay: !input "no_motion_wait"
  - service: light.turn_off
    target: !input "light_target"
    data:
      transition: !input "transition_time"
