blueprint:
  name: Motion-activated Light with Adjustable Brightness and Transition
  description: >-
    Turn on a light with specified brightness and transition times when motion
    is detected. Brightness changes based on time of day.
  domain: automation
  source_url: https://github.com/orHayoun/ha/blob/main/motion_light_v2.yaml
  author: Home Assistant
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    transition_time:
      name: Transition Time
      description: Time it takes for the light to turn on or off.
      default: 2
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds
    day_brightness:
      name: Day Brightness
      description: Brightness level for the light during the day.
      default: 100
      selector:
        number:
          min: 0
          max: 255
    evening_brightness:
      name: Evening Brightness
      description: Brightness level for the light during the evening.
      default: 70
      selector:
        number:
          min: 0
          max: 255
    night_brightness:
      name: Night Brightness
      description: Brightness level for the light during the night.
      default: 30
      selector:
        number:
          min: 0
          max: 255

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - alias: "Calculate Brightness Based on Time of Day"
    choose:
      - conditions: "{{ now().hour >= 6 and now().hour < 18 }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness: "{{ day_brightness | int }}"
              transition: "{{ transition_time | int }}"
      - conditions: "{{ now().hour >= 18 and now().hour < 22 }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness: "{{ evening_brightness | int }}"
              transition: "{{ transition_time | int }}"
      - conditions: "{{ now().hour >= 22 or now().hour < 6 }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness: "{{ night_brightness | int }}"
              transition: "{{ transition_time | int }}"
  - alias: "Wait for no motion"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Delay"
    delay: "{{ no_motion_wait | int }}"
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
    data:
      transition: "{{ transition_time | int }}"

